6.6: Redux-anecdotes-v2: update to React 16.6.3
It looks like 16.2.0 is too old of a version of React when using react-redux
6.0.0 and causes the following error:

TypeError: __WEBPACK_IMPORTED_MODULE_0_react___default.a.createContext is not a
function

Updating to 16.6.3 resolves this issue.